# -*- encoding: utf-8 -*-
#
#
# Bista Solutions Pvt. Ltd
# Copyright (C) 2012 (http://www.bistasolutions.com)
#
#

{
    'name': "TDCC Operations",
    'version': "1.0",
    'depends': ['stock','sale_crm', 'purchase', 'account_cancel',
                'web_export_view', 'account_accountant',
                'account_deferred_revenue',
                'bista_sms_global'],
    'author': "Bista Solutions",
    'website': "www.bistasolutions.com",
    'category': "TDCC",
    'summary': "Manage TDCC Operations",
    'description': """
    """,
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/accout_journal_data.xml',
        'data/res.company.csv',
        'data/week_days_data.xml',
        'data/product_category_data.xml',
        'data/mail_activity_data.xml',
        'data/sales_team_data.xml',
        'data/partner_mail_templates.xml',
        'data/group_appointment_booking_templates.xml',
        'reports/eip_registration_form_report.xml',
        'reports/report_eip_registration_form_template.xml',
        'reports/appointment_list_report_template.xml',
        'wizard/cancel_appointment_views.xml',
        'wizard/additional_booking.xml',
        'wizard/wizard_update_clinical_note_view.xml',
        'wizard/wizard_invoice_cancel_request.xml',
        'wizard/wizard_payment_cancel_request.xml',
        'wizard/day_closing_views.xml',
        'wizard/manage_payment_view.xml',
        'wizard/update_appointment_state.xml',
        'views/web_client.xml',
        'views/email_view.xml',
        'views/mail_message_view.xml',
        'views/mail_activity_view.xml',
        'views/operations_views.xml',
        'views/appointment_appointment_views.xml',
        'views/partner_views.xml',
        'views/service_type_views.xml',
        'views/service_group_views.xml',
        'views/appointment_type_views.xml',
        'views/appointment_medium_views.xml',
        'views/appointment_cancel_reason_views.xml',
        'views/appointment_rearrange_reason_views.xml',
        'views/school_views.xml',
        'views/classroom_views.xml',
        'views/room_views.xml',
        'views/attendance_view.xml',
        'views/crm_lead_views.xml',
        'views/sale_order_views.xml',
        'views/account_invoice_views.xml',
        'views/public_holidays_views.xml',
        'views/transfer_form_views.xml',
        'views/academic_views.xml',
        'views/timetable_views.xml',
        'views/observation_views.xml',
        'views/physician_code_views.xml',
        'views/res_company_views.xml',
        'views/account_payment_view.xml',
        'wizard/plan_week_schedule_view.xml',
        'wizard/date_comfortable_view.xml',
        'views/group_appointment_views.xml',
        'views/group_appointment_booking_views.xml',
        'reports/transfer_form_report.xml',
        'data/appointment_appointment_data.xml',
        'data/appointment_mail_template.xml',
        'wizard/reschedule_appointment_views.xml',
        'reports/time_table_report.xml',
        'reports/report_observation_form_template.xml',
        'views/common_cancellation_views.xml',
        'views/common_rearrangement_views.xml',
        'wizard/daily_appointment_wizard_views.xml',
        'views/daily_appointment_views.xml',
        'views/product_views.xml',
        'views/account_invoice_read_view.xml',
        'views/daily_notes_views.xml',
        'views/account_deferred_revenue.xml',
        'reports/report_appointment_appointment_template.xml',
        'reports/appointment_appointment_report.xml',
        'reports/daily_appointment.xml',
        'reports/payment_report.xml',
        'data/account_payment_mail_template.xml',
    ],
    'demo': [
    ],
    'qweb': ["static/src/xml/daily_notes_dashboard.xml"],
    'installable': True,
    'application': True,
    'auto_install': False
}
